# You can set these variables from the command line.
ROOT          = .
THIS_FILE    := $(lastword $(MAKEFILE_LIST))
TEST_DIR      = $(ROOT)
TEST_CMD      = nosetests --with-coverage --cover-erase --cover-html
PIP_CMD       = pip3
DEPENDS       = $(ROOT)/requirements.txt
DOCDIR        = $(ROOT)/docs
CACHE_PATTERN = .*\(\.pyc\|__pycache__\)

.PHONY: help
help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  depends    to install all dependencies"
	@echo "  docs       to generate docs for digital certificate"

.PHONY: test
test:
	$(shell cd $(TEST_DIR); $(TEST_CMD))

.PHONY: depends
depends:
	$(PIP_CMD) install -r $(DEPENDS)


